# -*- coding: utf-8 -*-
"""Cloudantdb_creation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18_PhG0bBX9G08gNoS9I2geukkLdfi0cK
"""

!pip install cloudant

from cloudant.client import Cloudant

client=Cloudant.iam("74ac98ce-3435-4520-a264-781952519325-bluemix", "y9YYPnQ1-s8IDmcgAyJ4AxtixGiWNj1JDZ4K9QBVrrPV", connect=True)

my_database=client.create_database("my_database")